version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
​
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
​
    working_directory: ~/web-frontend-tests
​
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
​
    steps:
      - checkout
      - run:
         name: "Build"
         command: |
          mvn test
          
          
workflows:
  version: 2.1
  commit-workflow:
    jobs:
      - build
  scheduled-workflow-1:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only: 
                - master
